intellij-dlanguage/intellij-dlanguage

exampleCode/mixins.d
Here's some simplified mixin examples.
=> start of example code

src/main/java/net/masterthought/dlanguage/module/DLanguageDubModuleBuilder.java
=> added -n to dub options to prevent interactive menu

src/main/java/net/masterthought/dlanguage/actions/CreateDLanguageClassAction.java, src/main/resources/META-INF/plugin.xml, src/main/resources/fileTemplates/internal/D Language Class.d.ft
I added a create class menu as requested by #96.
Please check this before merging, because I am unsure that this is perfect.
=> added create class option

src/main/java/net/masterthought/dlanguage/actions/DFixAction.java, src/main/java/net/masterthought/dlanguage/highlighting/annotation/external/CompileCheck.java, src/main/java/net/masterthought/dlanguage/highlighting/annotation/external/DScanner.java, src/main/java/net/masterthought/dlanguage/module/DLanguageDubModuleBuilder.java, src/main/java/net/masterthought/dlanguage/project/DubConfigurationParser.java, src/main/java/net/masterthought/dlanguage/utils/ExecUtil.java
I fixed some deprecated method usages.
=> Fixed deprecated methods.

src/main/java/net/masterthought/dlanguage/stubs/types/UnitTestingStubElementType.java
#167 was caused by a badly written serialize/deserialize method.
=>  Bug fix for #167. Fixes eof exception.

src/main/java/net/masterthought/dlanguage/utils/ExecUtil.java
=> Windows dub executable finding fixes

gen/net/masterthought/dlanguage/psi/DLanguageIdentifier.java, gen/net/masterthought/dlanguage/psi/impl/DLanguageIdentifierImpl.java, src/main/java/net/masterthought/dlanguage/codeinsight/dcd/DCDCompletionServer.java, src/main/java/net/masterthought/dlanguage/features/DFoldingBuilder.java, src/main/java/net/masterthought/dlanguage/grammar/DLanguage.bnf, src/main/java/net/masterthought/dlanguage/psi/impl/DPsiImplUtil.java, src/main/java/net/masterthought/dlanguage/psi/references/DReference.java, src/main/java/net/masterthought/dlanguage/refactoring/DRefactoringSupportProvider.java, src/main/resources/META-INF/plugin.xml
I added safe delete support and fixed some deprecated method usages in DCDCompletionServer
=> Safe delete and deprecated methods

src/main/resources/i18n_en_US.properties, src/main/resources/i18n_fr_FR.properties
The title pretty much says it all. Some of the French translations where not easy(some technical terms don't translate/I'm not sure what the agreed upon terms are). There may be inaccuracies in the translations, and would be best to get feedback from a developer in France.
=> Added French and US translations

src/main/java/net/masterthought/dlanguage/highlighting/annotation/external/CompileCheck.java, src/main/java/net/masterthought/dlanguage/highlighting/annotation/external/DExternalAnnotator.java, src/main/kotlin/net/masterthought/dlanguage/inspections/PossiblyUndefinedSymbol.kt, src/main/kotlin/net/masterthought/dlanguage/processors/DCompletionProcessor.kt, src/main/kotlin/net/masterthought/dlanguage/psi/references/DReference.kt
The fix for #232 does fix the problem, however it is still possible that the hang could occur if intellij is unable to save all files when starting up the commit dialog.The fix for #235 is a partial fix until I can get type deduction working.
=> Issue fixes for #235,#234, and #232

src/main/java/net/masterthought/dlanguage/parser/DLangParser.java
=> Fixed issue #247

src/main/kotlin/io/github/intellij/dlanguage/processors/DCompletionProcessor.kt, src/main/kotlin/io/github/intellij/dlanguage/psi/references/DReference.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/DTopLevelDeclarationsByModule.kt
Title says it all. Fix applies only to within import declarations and not elsewhere,
=> Fixed #257

src/main/java/io/github/intellij/dlanguage/psi/impl/named/DlangIdentifierImpl.java, src/main/java/io/github/intellij/dlanguage/psi/impl/named/DlangSingleImportImpl.java, src/main/java/io/github/intellij/dlanguage/stubs/DlangSingleImportStub.java, src/main/java/io/github/intellij/dlanguage/stubs/types/SingleImportStubElementType.java, src/main/kotlin/io/github/intellij/dlanguage/resolve/DResolveUtil.kt, src/main/kotlin/io/github/intellij/dlanguage/resolve/processors/DNameScopeProcessor.kt, src/main/kotlin/io/github/intellij/dlanguage/resolve/processors/basic/BasicResolve.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/DlangUnionDeclarationStub.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/DImportIndex.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/DModuleDeclarationIndex.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/DTopLevelDeclarationIndex.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/DTopLevelDeclarationsByModule.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/MembersIndex.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/types/DlangUnionDeclarationStubElementType.kt
Title says it all.I fixed a few minor bug I noticed in the process of debugging #263.
=> Fix for issue #263

src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImpl.kt
=> Issue #266 fixed.

src/main/java/io/github/intellij/dlanguage/actions/ProcessDLibs.java, src/main/java/io/github/intellij/dlanguage/project/DubConfigurationParser.java
As well as fixing the process d libs action, it will now fetch dependencies if dub has not fetched them yet.
=> Issue #223: ProcessDLibs works again. 

src/main/java/io/github/intellij/dlanguage/psi/impl/DNamedStubbedPsiElementBase.java, src/main/java/io/github/intellij/dlanguage/psi/impl/named/DLanguageModuleDeclarationImpl.java, src/main/java/io/github/intellij/dlanguage/psi/impl/named/DlangSingleImportImpl.java
=> Fix for #279

src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java, src/main/java/io/github/intellij/dlanguage/parser/Token.java
This fixes #255
It should now say `Expected an Identifier instead of ";"`
=> Made better parser error messages.

src/main/java/de/halirutan/mathematica/errorreporting/IdeaInformationProxy.java, src/main/java/io/github/intellij/dlanguage/actions/DFixAction.java, src/main/java/io/github/intellij/dlanguage/actions/DFormatAction.java, src/main/java/io/github/intellij/dlanguage/actions/ProcessDLibs.java, src/main/java/io/github/intellij/dlanguage/actions/RestartDCD.java, src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionClient.java, src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServer.java, src/main/java/io/github/intellij/dlanguage/errorreporting/DErrorReporter.java, src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/CompileCheck.java, src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/DScanner.java, src/main/java/io/github/intellij/dlanguage/module/DlangDubModuleBuilder.java, src/main/java/io/github/intellij/dlanguage/run/DlangRunDubState.java, src/main/java/io/github/intellij/dlanguage/settings/DLanguageToolsConfigurable.java, src/main/java/io/github/intellij/dlanguage/settings/ToolKey.java, src/main/java/io/github/intellij/dlanguage/unittest/DUnitTestRunProcessHandler.java, src/main/java/uk/co/cwspencer/ideagdb/debug/GdbDebugProcess.java
This pull request makes sentry record versions for various DTools, at the cost of each DTool being global instead of project specific.
=> Make sentry record plugin/dscanner/dub/etc version 

src/main/java/io/github/intellij/dlanguage/run/RunUtil.java
For now i just added a a better message for the error. I could add a error popup but first i need to get a better understanding of the Jetbrains API.
=> Added better message for trying to start debugger without path to gdb

src/main/java/io/github/intellij/dlanguage/features/DChooseByNameContributor.java, src/main/java/io/github/intellij/dlanguage/features/DClassContributor.java
=> Added Enum and Structs to Navigation/Class

CONTRIBUTING.md
They didn't show up in strict markdown viewers as headers
=> Fix headers in CONTRIBUTING.md

src/main/java/io/github/intellij/dlanguage/settings/DLanguageToolsConfigurable.form, src/main/java/io/github/intellij/dlanguage/settings/DLanguageToolsConfigurable.java, src/main/kotlin/io/github/intellij/dlanguage/psi/references/DReference.kt
=> Improved the settings UI

src/main/java/io/github/intellij/dlanguage/DlangSdkType.java
Now additionally covers the Arch directory layout, as well as /usr/local for those who install there.
=> expand path lookup locations on *nix systems

src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/DScanner.java
With this PR the D-Scanner flags field is now taken into account
=> Take D-Scanner flags settings field into account

src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServer.java
In DMD Compiler SDK screen the paths to phobos and druntime/import is already determined. Or you can manually set the paths at a central place.
This information can be used for DCD server and D-Scanner.
For D-Scanner pr is also created https://github.com/intellij-dlanguage/intellij-dlanguage/pull/463
=> DCD Server: Use SDK compiler source paths

src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/DScanner.java
The compiler sources from SDK are used for D-Scanner as import paths
=> D-Scanner: Use SDK compiler source paths

src/main/java/io/github/intellij/dlanguage/codeinsight/DCompletionContributor.java, src/main/java/io/github/intellij/dlanguage/codeinsight/DCompletionProvider.java, src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionClient.java, src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServer.java
=> Make the DCD completions async

.github/workflows/coverage.yml, .github/workflows/gradle.yml, .github/workflows/publish.yml, .travis.yml, build.gradle, errorreporting/src/main/java/io/github/intellij/dlanguage/errorreporting/DErrorReporter.java, errorreporting/src/main/kotlin/io/github/intellij/dlanguage/errorreporting/sentry.kt, gradle.properties, src/main/kotlin/io/github/intellij/dlanguage/DLanguage.kt, src/main/resources/META-INF/plugin.xml, utils/src/main/java/io/github/intellij/dlanguage/utils/GuiUtil.java
This fixed support for 2020.3 #602 
This is a download to the plugin
[intellij-dlanguage-1.26.zip](https://github.com/intellij-dlanguage/intellij-dlanguage/files/6143883/intellij-dlanguage-1.26.zip)
=> Feature/intellij 2020.3 support

src/main/kotlin/io/github/intellij/dlanguage/actions/CreateDlangClassAction.kt, src/test/kotlin/io/github/intellij/dlanguage/actions/CreateDlangClassActionTest.kt
=>  #667 fix allowed modules names according to the Specs

src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/DScanner.java
When file is 1 line, the line index is 0 not 1
closes #697
=>  #697 Fix DScanner notification position wrongly computed

src/main/kotlin/io/github/intellij/dlanguage/folding/DFoldingBuilder.kt, src/test/kotlin/io/github/intellij/dlanguage/folding/DFoldingBuilderTest.kt, src/test/resources/gold/folding/one_liner_import.d
=> #726: don’t fold single line imports

src/main/java/io/github/intellij/dlanguage/settings/DLanguageToolsConfigurable.java
When the update was done in the thread and that we close the window, the
thread try to update a field to a window that is being deleted. For some
reason this was making the IDE to hang due to a deadlock.
This fix prevent deadlock by ensuring all threads that could modify a
field is stopped before releasing the window
Close #684 
The way I did the fix also probably close #677 (I tested and wasn’t able to reproduce)
=>  #684 Prevent IDE to hangs when configuring Tools

src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java, src/test/java/io/github/intellij/dlanguage/parser/DLanguageParserTest.java, src/test/resources/gold/parser/expected/statements_unterminated_if.txt, src/test/resources/gold/parser/statements_unterminated_if.d
=> #737: fix nullpointer exception in parser for an unterminated if

src/main/java/io/github/intellij/dlanguage/psi/impl/DElementFactory.java, src/main/java/io/github/intellij/dlanguage/psi/impl/named/DlangIdentifierImpl.java, src/main/kotlin/io/github/intellij/dlanguage/quickfix/SwitchToNewAliasSyntax.kt, src/test/java/io/github/intellij/dlanguage/psi/impl/DElementFactoryTest.java, src/test/java/io/github/intellij/dlanguage/psi/named/DlangIdentifierTest.java, src/test/kotlin/io/github/intellij/dlanguage/codeinsight/linemarker/DubExecutableRunLineMarkerContributorTest.kt, src/test/kotlin/io/github/intellij/dlanguage/psi/references/DReferenceTest.kt
some of these tests aren't particularly useful but it's better than nothing
=> added some tests for DElementFactory, DlangIdentifier, and DReference

build.gradle
This fix intellij dependencies not found:
https://github.com/JetBrains/gradle-intellij-plugin/issues/1209
=> Update gradle intellij plugin

src/main/kotlin/io/github/intellij/dlanguage/dub/packageConfig/DubJsonSchemaProviderFactory.kt, src/main/kotlin/io/github/intellij/dlanguage/dub/packageConfig/inspections/DubPackageDependencyVisitor.kt, src/main/kotlin/io/github/intellij/dlanguage/dub/packageConfig/inspections/PackageVersionInspection.kt, src/main/resources/META-INF/dub.xml, src/main/resources/META-INF/plugin.xml, src/main/resources/inspectionDescriptions/PackageNotFound.html, src/main/resources/inspectionDescriptions/PackageVersionValidation.html, src/main/resources/jsonSchema/dub.json-schema.json, src/test/kotlin/io/github/intellij/dlanguage/dub/packageConfig/inspections/JsonInvalidVersionInspectionsTest.kt
- Add JSON Schema to allow autocompletion of dub.json file
- Add version format validator for packages
=> Dub json config improvements

build.gradle, debugger/build.gradle, errorreporting/build.gradle, sdlang/build.gradle, utils/build.gradle
Remove the version of plugins for submodules, they are already set in parent.
Remove the commented and empty parts, they are reducing the clarity
Apply common routines in all Project to not have to repeat it in all submodules
=> Rework gradle to improve mainanability

dub/src/main/kotlin/io/github/intellij/dub/toolwindow/DubToolWindow.kt
This should close #826
I was not able to reproduce it locally, tell me if it doesn’t fix the bug
=> #826 fix potential nullpointer exception

build.gradle, src/main/resources/META-INF/copyright.xml, src/main/resources/META-INF/plugin.xml
=>  #837 Add copyright support

src/main/kotlin/io/github/intellij/dlanguage/features/DCommenter.kt, src/main/kotlin/io/github/intellij/dlanguage/features/DDocumentationProvider.kt, src/main/kotlin/io/github/intellij/dlanguage/features/documentation/DSignatureDocGenerator.kt, src/main/kotlin/io/github/intellij/dlanguage/resolve/processors/parameters/DAttributesFinder.kt, src/test/kotlin/io/github/intellij/dlanguage/features/DDocumentationProviderTest.kt
Depends on fixes bring by #854 to work
Closes #856
=> Fix 856/better populate render doc popup

src/main/java/io/github/intellij/dlanguage/codeinsight/DCompletionProvider.java, src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/DScanner.java
Got sick of errors constantly so here are a couple more fixes to EDT.
Also covers #790
=> DScanner + DCompletionProvider fix wrong thread access (EDT)

dub/src/main/kotlin/io/github/intellij/dub/project/DubConfigurationParser.kt, dub/src/main/kotlin/io/github/intellij/dub/project/DubProjectImportBuilder.kt
Fixes a crash (exception) when importing a dub module (project not the D module).
Basically when you have a project already created, and try to import a dub project into a Intellij module via the Project Structure window, it'll throw an exception.
Also fixed a problem with the no dub configured notification. So it won't show configure twice with only one that actually works.
=> Fix importing of a dub module

src/main/kotlin/io/github/intellij/dlanguage/structure/DStructureViewElement.kt
=> Fix #889 fix navigation through project structure

src/main/kotlin/io/github/intellij/dlanguage/resolve/DResolveUtil.kt, src/main/kotlin/io/github/intellij/dlanguage/resolve/processors/basic/BasicResolve.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTestCase.kt, src/test/resources/gold/resolve/scopeOperatorDotXResolveGlobal/scope_operator.d, src/test/resources/gold/resolve/scopeOperatorDotXResolveGlobalWithImport/declaration.d, src/test/resources/gold/resolve/scopeOperatorDotXResolveGlobalWithImport/scope_operator.d, src/test/resources/gold/resolve/scopeOperatorXResolveLocal/scope_operator.d
As explained https://dlang.org/spec/module.html#module_scope_operators the .x should not resolve to the parameter but to the module declared x variable.
=> Implement the module scope operator resolution

src/main/kotlin/io/github/intellij/dlanguage/resolve/DResolveUtil.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/DImportIndex.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/DTopLevelDeclarationIndex.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/DTopLevelDeclarationsByModule.kt, src/main/kotlin/io/github/intellij/dlanguage/stubs/index/StubIndexUtil.kt, src/test/kotlin/io/github/intellij/dlanguage/psi/references/DReferenceTest.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DImportsUsageResolveTest.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTestCase.kt, src/test/resources/gold/resolve/constructorCallResolveParameters/definition.d, src/test/resources/gold/resolve/constructorCallShouldResolveConstructorWithClassDeclarationInTheSameFile/with_class.d
Nested struct is not a top level declaration.
Closes #895
=>  #985 Fix top level declaration definition for reject nested structs

src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java, src/main/java/io/github/intellij/dlanguage/parser/ParserWrapper.java, src/main/java/io/github/intellij/dlanguage/psi/DlangTypes.java, src/main/java/io/github/intellij/dlanguage/psi/DlangVisitor.java, src/main/java/io/github/intellij/dlanguage/psi/impl/DElementTypeFactory.java, src/main/java/io/github/intellij/dlanguage/psi/impl/named/DlangDeclaratorIdentifierImpl.java, src/main/java/io/github/intellij/dlanguage/psi/named/DlangDeclaratorIdentifier.java, src/main/java/io/github/intellij/dlanguage/stubs/DlangDeclaratorIdentifierStub.java, src/main/java/io/github/intellij/dlanguage/stubs/types/DeclaratorIdentifierStubElementType.java, src/main/kotlin/io/github/intellij/dlanguage/resolve/DResolveUtil.kt, src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImplUtil.kt, src/main/kotlin/io/github/intellij/dlanguage/utils/ShortenedNames.kt, src/main/resources/types_regen_script.d, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt, src/test/resources/gold/parser/expected/expressions_is.txt, src/test/resources/gold/resolve/aliasUsageToAliasDeclarationSecondAliasForm/alias_usage.d, src/test/resources/gold/resolve/aliasUsageToAliasDeclarationSecondAliasFormWithImport/alias_definition.d, src/test/resources/gold/resolve/aliasUsageToAliasDeclarationSecondAliasFormWithImport/alias_usage.d
The usages of alias in form `alias int FOO` will now be resolved correctly
=> Fix alias resolution

build.gradle.kts, gradle/libs.versions.toml, sdlang/build.gradle.kts, src/test/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServerTest.java, src/test/kotlin/io/github/intellij/dlanguage/LightDlangTestCase.kt
=>  #920 upgrade grammarkit plugin to fix build with version 2024.1

src/main/kotlin/io/github/intellij/dlanguage/utils/DPsiUtil.kt, src/main/kotlin/io/github/intellij/dlanguage/utils/ParameterCountRange.kt
This files is only used in file in utils and has nothing to do with resolve.
=> Move ParameterCountRange to utils

src/main/java/io/github/intellij/dlanguage/DlangSdkType.java
=> fix autodetect of dmd for new projects on linux

src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java, src/main/kotlin/io/github/intellij/dlanguage/presentation/Utils.kt, src/main/kotlin/io/github/intellij/dlanguage/structure/DStructureViewElement.kt, src/main/kotlin/io/github/intellij/dlanguage/utils/ShortenedNames.kt, src/main/resources/types_regen_script.d, src/test/resources/gold/parser/expected/arrays_initialization.txt, src/test/resources/gold/parser/expected/attributes_user_defined.txt, src/test/resources/gold/parser/expected/bug_fixes.txt, src/test/resources/gold/parser/expected/enums.txt, src/test/resources/gold/parser/expected/expressions_is.txt, src/test/resources/gold/parser/expected/properties_stringof.txt, src/test/resources/gold/parser/expected/traits_getattributes.txt, src/test/resources/gold/parser/expected/type_implicit_conversion.txt, utils/src/main/kotlin/io/github/intellij/dlanguage/core.kt
Actually improve the whole structure
closes #960
closes #962
=> #960 fix structure view pointers and handle ConditionalDeclaration

.gitignore, build.gradle.kts, debugger/build.gradle.kts, dlang/plugin-impl/build.gradle.kts, dlang/plugin-impl/src/main/resources/META-INF/plugin.xml, dub/build.gradle.kts, errorreporting/build.gradle.kts, gradle.properties, gradle/libs.versions.toml, sdlang/build.gradle.kts, utils/build.gradle.kts
https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html
Note: cool thing with the version 2 of intellij patform gradle plugin is that things are more de-correlated (to idea product) and more flexible. We can now see more easily what is specific to intellij even in tests. This will help a lot to refactor the project and allow better integration with clion.
https://blog.jetbrains.com/platform/2024/07/intellij-platform-gradle-plugin-2-0/
=> Upgrade intellij gradle plugin to 2.x

.github/workflows/coverage.yml, build.gradle.kts, debugger/build.gradle.kts, dlang/plugin-impl/build.gradle.kts, dub/build.gradle.kts, errorreporting/build.gradle.kts, gradle/libs.versions.toml, sdlang/build.gradle.kts, utils/build.gradle.kts
=> Re enable coverage

.github/workflows/coverage.yml
Disable gradle config caching for now due to an issue with this https://github.com/kt3k/coveralls-gradle-plugin/issues/117
=> Fix coveralls build

dlang/plugin-impl/src/main/resources/META-INF/plugin.xml
remove an unexistent service (deleted by
f70d3b03ed8d81fd7873cbb72c0b9cf6992facbb)
and fix include names
=> Fix plugin.xml

src/test/kotlin/io/github/intellij/dlanguage/folding/DFoldingBuilderTest.kt, src/test/resources/gold/folding/static_foreach.d
=>  #948 Add a test for the static foreach folding

dlang/psi-api/src/main/java/io/github/intellij/dlanguage/psi/interfaces/LabelQualifier.java, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/ext/DLanguageBreakStatementImplMixin.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/ext/DLanguageContinueStatementImplMixin.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/ext/DLanguageGotoStatementImplMixin.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/references/LabelReference.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/resolve/processor/LabelProcessor.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/PsiScopesUtil.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImpl.kt, scripts/types_regen_script.d, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt, src/test/resources/gold/resolve/continueToLabeledStatementShouldResolve/usage.d, src/test/resources/gold/resolve/gotoToLabeledStatementShouldResolve/usage.d
They can used only by goto, continue, and break
=> Resolve label elements

gradle/libs.versions.toml
We are running version of Junit 4 and not 1
=> fix the junit version

dlang/psi-impl/src/main/java/io/github/intellij/dlanguage/psi/impl/named/DLanguageFunctionDeclarationImpl.java, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/ext/DLanguageTypeImplMixin.kt, src/test/kotlin/io/github/intellij/dlanguage/types/AutoValueAssignmentTypeTest.kt, src/test/kotlin/io/github/intellij/dlanguage/types/FunctionReturnTypeTest.kt
And add some test to cover properties a bit
=> Fix type of function call return type (with suffix, like arrays)

src/test/kotlin/io/github/intellij/dlanguage/folding/DFoldingBuilderTest.kt, src/test/resources/gold/folding/scope_statement.d, src/test/resources/gold/folding/static_if.d
can closes #1013 (depending on @rikkimax expectations about folding)
=> fix(1013): add tests to cover folding of elements

dlang/psi-api/src/main/java/io/github/intellij/dlanguage/psi/DlangVisitor.java, dlang/psi-api/src/main/kotlin/io/github/intellij/dlanguage/utils/ShortenedNames.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/impl/DLanguageImportDeclarationImpl.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/PsiScopesUtil.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImpl.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImplUtil.kt, scripts/types_regen_script.d, src/main/kotlin/io/github/intellij/dlanguage/features/DDocumentationProvider.kt, src/main/kotlin/io/github/intellij/dlanguage/features/documentation/DSignatureDocGenerator.kt, src/test/kotlin/io/github/intellij/dlanguage/psi/TestImportVisibility.kt
=> improve visibility resolving

dlang/plugin-impl/src/main/resources/META-INF/plugin.xml, dub/src/main/kotlin/io/github/intellij/dub/actions/ProcessDLibs.kt, dub/src/main/kotlin/io/github/intellij/dub/project/DubConfigFileListener.kt, dub/src/main/kotlin/io/github/intellij/dub/project/DubConfigurationParser.kt, dub/src/main/kotlin/io/github/intellij/dub/project/DubProjectImportBuilder.kt, dub/src/main/kotlin/io/github/intellij/dub/run/DlangRunDubState.kt, src/main/java/io/github/intellij/dlanguage/actions/DFormatAction.java, src/main/java/io/github/intellij/dlanguage/actions/RestartDCD.java, src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServer.java, src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/DScanner.java, src/main/java/io/github/intellij/dlanguage/run/DlangRunAppState.java, src/main/java/io/github/intellij/dlanguage/run/DlangRunDmdState.java, src/main/java/io/github/intellij/dlanguage/run/RunUtil.java, src/main/java/io/github/intellij/dlanguage/unittest/DUnitTestRunProcessHandler.java
Replace `Notifications.Bus` with `NotificationGroupManager`
=> enhancement (#654): apply new syntax for notifications

build.gradle.kts, debugger/build.gradle.kts, dlang/plugin-impl/build.gradle.kts, dlang/psi-api/build.gradle.kts, dlang/psi-impl/build.gradle.kts, dub/build.gradle.kts, errorreporting/build.gradle.kts, gradle/libs.versions.toml, sdlang/build.gradle.kts, utils/build.gradle.kts
And remove unnecessary calls to helper (not necessary since 2.2.0)
=> Update the intellij gradle platform plugin to 2.3.0

dlang/psi-impl/src/main/java/io/github/intellij/dlanguage/psi/impl/named/DLanguageForeachTypeImpl.java
foreach.expression can actually be null
=> Fix null pointer exception

build.gradle.kts, dlang/plugin-impl/build.gradle.kts
This fixes tests with intellij gradle platform module 2.4.0+
=> Add a missing json module in bundled modules for the plugin

src/main/java/io/github/intellij/dlanguage/DlangSdkType.java
=> fix(#1079): ensure write lock is held during sdk save

dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/DlangPsiFileImpl.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/PsiScopesUtil.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/processor/UFCSProcessor.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImpl.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImplUtil.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTestCase.kt, src/test/resources/gold/resolve/functionCallUFCS/resolve.d, src/test/resources/gold/resolve/functionCallUFCSWithLocalImport/other.d, src/test/resources/gold/resolve/functionCallUFCSWithLocalImport/resolve.d, src/test/resources/gold/resolve/functionCallUFCSWithLocalImportResolveLocalFunction/other.d, src/test/resources/gold/resolve/functionCallUFCSWithLocalImportResolveLocalFunction/resolve.d, src/test/resources/gold/resolve/functionCallUFCSWithLocalReferenceSameName/resolve.d
=> Fix 1014 resolve with ufcs

dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/DlangPsiFileImpl.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/ext/DLanguageReferenceExpressionImplMixin.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/references/ImportBindReference.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/PsiScopesUtil.kt, dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImpl.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DImportsUsageResolveTest.kt, src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt, src/test/kotlin/io/github/intellij/dlanguage/types/AutoValueAssignmentTypeTest.kt, src/test/resources/gold/resolve/functionCallUFCSWithLocalImportResolveLocalFunction/resolve.d, src/test/resources/gold/resolve/functionCallUFCSWithLocalSelectiveImportResolve/other.d, src/test/resources/gold/resolve/functionCallUFCSWithLocalSelectiveImportResolve/resolve.d
Fixes some left CTFE cases (import bind)
Fix a type with ".ptr" usage
=> Ctfe resolve fixes

dlang/plugin-impl/src/main/resources/META-INF/plugin.xml, dub/src/main/resources/META-INF/io.github.intellij.dub.xml, src/main/kotlin/io/github/intellij/dlanguage/run/RunAppRunner.kt
This class has nothing to do with dub, so move it outside of the dub module to reduce confusion.
=> Move the RunAppRunner class from dub module to the main module

dlang/plugin-impl/src/main/resources/META-INF/plugin.xml
Now files icons reappear as expected
=> Fix path of optionally included xml

errorreporting/src/main/kotlin/io/github/intellij/dlanguage/errorreporting/sentry.kt
switch to kotlin coroutines (modern idea threading way)
add more available data from the event (attachments)
remove deprecated class cast
It shouldn’t break integration but I didn’t tested it
=> Modernize sentry integration
