intellij-dlanguage/intellij-dlanguage

- README.md
Modifying the Info.plist file will invalidate the application signature, which makes updating a pain. The proper method for forcing IntelliJ to run under a higher JDK is to copy the `idea.properties` to your user preferences instead ([see here for more info](http://stackoverflow.com/questions/13578062/how-to-increase-ide-memory-limit-in-intellij-idea-on-mac/13581526#13581526)).
> Change instructions for forcing 1.7* JVM on OS X

- src/main/java/net/masterthought/dlanguage/highlighting/annotation/external/CompileCheck.java
Several problems prevented the CompileCheck from properly parsing and reporting DUB errors:
- The regex did not take into account the column number specifier
- The regex did not take sourcefiles in sub-directories into account
- The check whether the error applied to the current source file did not take sub-directories into account
- DUB messages which weren't problem reports also got added to the problem output
This pull fixes these issues and cleans up the CompileCheck class somewhat
> Fix DUB-based error highlighting

- build.gradle
- src/main/java/io/github/intellij/dlanguage/DlangSdkType.java
- src/main/java/io/github/intellij/dlanguage/module/DlangDubModuleBuilder.java
- src/main/java/io/github/intellij/dlanguage/module/DlangModuleBuilder.java
- src/main/java/io/github/intellij/dlanguage/project/CLionDubProjectOpenProcessor.java
- src/main/java/io/github/intellij/dlanguage/project/DubProjectImportBuilder.java
- src/main/java/io/github/intellij/dlanguage/project/DubProjectOpenProcessor.java
- src/main/java/io/github/intellij/dlanguage/utils/GuiUtil.java
- src/main/kotlin/io/github/intellij/dlanguage/project/creation.kt
- src/main/resources/META-INF/clion-only.xml
- src/main/resources/META-INF/idea-only.xml
- src/main/resources/META-INF/plugin.xml
* basic ProjectOpenProcessor to open dub-based projects in CLion
* extract IDEA-only plugin dependencies
* replace usages of IDEA-only APIs with generic APIs
* auto-detect dmd compiler from MacPorts
More details are provided in the inline comments
> #57 further CLion support: opening existing projects, auto detect dmd compiler, APIs cleanup

- src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServer.java
Path has value "C:\D\dmd2\windows\bin" on windows.
Phobos is located at C:\D\dmd2\src\phobos
and druntime is located at C:\D\dmd2\src\druntime\import
> Fix DCD druntime/phobos path on windows

- src/main/java/io/github/intellij/dlanguage/project/DubConfigurationParser.java
- src/main/java/io/github/intellij/dlanguage/run/DubBuildRunner.java
- src/main/java/io/github/intellij/dlanguage/run/RunUtil.java
- src/main/java/uk/co/cwspencer/gdb/Gdb.java
- src/main/java/uk/co/cwspencer/gdb/gdbmi/GdbMiParser2.java
- src/main/java/uk/co/cwspencer/ideagdb/debug/GdbDebugProcess.java
- src/main/java/uk/co/cwspencer/ideagdb/debug/GdbExecutionStack.java
- src/main/java/uk/co/cwspencer/ideagdb/debug/GdbExecutionStackFrame.java
- src/main/java/uk/co/cwspencer/ideagdb/debug/breakpoints/GdbBreakpointHandler.java
- src/main/java/uk/co/cwspencer/ideagdb/debug/utils/SdkUtil.java
- src/main/kotlin/io/github/intellij/dlanguage/project/dependencies.kt
- src/main/kotlin/io/github/intellij/dlanguage/tools/dub/DescribeParser.kt
This pull requests enables MagoMI as GDB replacement on windows and also debugging linux applications on Windows using Windows Subsystem for linux.
Debugging is possible, variables are shown and stack trace is also working now. 
For testing create a batch file "dubwsl.bat" with content:
```
@ECHO OFF
wsl dub %*
```
and a batch file "gdbwsl.bat" with content:
```
@ECHO OFF
wsl gdb %*
```
Set dubwsl.bat as dub file path and gdbwsl.bat as gdb file path.
-var-update command bug is fixed and debugging is also possible now. But there are some issues with the stack trace:
- Variable content seems to be wrong
- app.d is mentioned 2 times (https://github.com/rainers/mago/issues/21) -> DMD bug?
Find newest mago-mi here
https://ci.appveyor.com/project/rainers/mago
This pr also introduce the dub …
> Enable MagoMI / GDB on Windows Subsystem for linux 

- src/main/java/io/github/intellij/dlanguage/run/DlangRunDubState.java
Environment variables set in DUB configuration were not passed while starting DUB.
Solves issue https://github.com/intellij-dlanguage/intellij-dlanguage/issues/95
> Use environment variables from dub configuration

- src/main/java/uk/co/cwspencer/ideagdb/debug/GdbValue.java
The missing return statement causes runtime errors
> Fix missing return statement in GdbValue.java

- src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServer.java
This might be a major change, but I think it is necessary.
The DCD server flags field had a special handling. While the user thought he can add arguments
like described on DCD documentation, that silently failed. Instead the values entered here were
splitted by comma and added fixed with -I prefix.
That was an unexpected behavior and not consistent to the other tools (dub/dscanner/gdb/...)
With the merged pull request #460 this special behavior isn't needed anymore. Compiler sources (phobos/druntime) + additional source paths can now be easily set in SDK settings. In most cases you doesn't need to add any sources anymore as phobos and druntime paths now be retrieved from SDK.
Therefore this PR removes the special handling. Flags are now passed as arguments as expected.
> Remove DCD special flags handling

- src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionServer.java
In case of an error with dcd it would be good to check the arguments dcd server was called with. This pr adds the dcd server arguments to the log.
> DCD Server command log added

- src/main/java/io/github/intellij/dlanguage/psi/DlangFile.java
- src/main/kotlin/io/github/intellij/dlanguage/projectview/DPsiFileNode.kt
- src/main/kotlin/io/github/intellij/dlanguage/projectview/DTreeStructureProvider.kt
- src/main/kotlin/io/github/intellij/dlanguage/projectview/ProjectViewUtil.kt
- src/main/resources/META-INF/idea-only.xml
- src/main/resources/META-INF/plugin.xml
This fixes #372 and should make it easier to customize the project view tree in the future.
In the new project view:
- The text shown for each D source file is the unqualified module name, instead of the fully qualified module name.
- If the module name and file name differ, both are shown (with the file name in grey).
- `package.d` files are shown with that name, rather than the module name.
- When "Sort by Type" is enabled, `package.d` files are listed at the top of their directory. All other files are sorted alphabetically by module name.
Side-by-side comparison, before and after:
Note that `test.d` and `example.d` have no explicit module declaration, so their fully qualified module names are `test` and `example` respectively.
The rename and file creation actions have the same issues …
> Implement custom TreeStructureProvider for project view

- debugger/src/main/java/uk/co/cwspencer/gdb/gdbmi/GdbMiParser2.java
This probably shouldn't be merged yet as it's only been tested on linux using GDB 8.3.1
It fixes #526 for me, however I'm unsure if this will have effect on mago-mi or gdb on macOS.
This PR removes "level" and "from" from the regex in `parseFrameLine`.  It also adds "arch" to the regex since that is included in the `line` as I'm seeing it.  I wanted to open this for review.  I will try to test this on Windows and macOS in the meantime to make sure it doesnt break anything else.
Thanks for your time!
> fix #526 - add 'arch' capture group to regex in parseFrameLine

- debugger/src/main/java/uk/co/cwspencer/ideagdb/debug/GdbConsoleView.form
The recent multimodule change broke the Gdb Console View becase the path to the class GdbConsoleView changed.
> Fix incorrect class binding for GdbConsoleView.form

- src/main/kotlin/io/github/intellij/dlanguage/quickfix/SwitchToNewAliasSyntax.kt
- src/test/kotlin/io/github/intellij/dlanguage/quickfix/DQuickFixTestBase.kt
- src/test/kotlin/io/github/intellij/dlanguage/quickfix/SwitchToNewAliasSyntaxTest.kt
- src/test/resources/gold/quickfix/afterSwitchToNewAlias.d
- src/test/resources/gold/quickfix/beforeSwitchToNewAlias.d
When running the `SwitchToNewAliasSyntax` quickfix, a declaration like
```d
alias Vector!(float, 3) vec3;
```
would be converted to
```d
alias  vec3 = Vector!(float, 3);
^^
```
This change removes the extra space preceeding the alias name.
> SwitchToNewAliasSyntax quickfix: make sure to trim the alias name.

- src/main/kotlin/io/github/intellij/dlanguage/features/formatter/DFormattingModelBuilder.kt
- src/test/java/io/github/intellij/dlanguage/formatting/DFormatterTest.java
- src/test/resources/gold/formatting/dlanguage_issue_497-after.d
Previous formatting behavior was to format
```d
foo(a, b, c);
```
as
```d
foo( a, b, c);
^ 
```
This was slightly surprising, especially as it is the result of a rule which appears to be intended to format switch statements. 
Ideally we'd probably support spacing options similar to the Java formatter, which lets you choose between `foo(x)`
and `foo( x )` though if there are strong feelings about keeping the current behavior then let's discuss.
> Formatter: don't format function call args with a leading space

- build.gradle
- src/main/kotlin/io/github/intellij/dlanguage/annotator/DHighlightingAnnotator.kt
- src/main/resources/META-INF/plugin.xml
- src/test/java/io/github/intellij/dlanguage/project/DubConfigurationParserTest.java
- src/test/kotlin/io/github/intellij/dlanguage/DLightPlatformCodeInsightFixtureTestCase.kt
- src/test/resources/gold/highlighting/annotator/type_parameters.d
When trying to build only one test (e.g. a parser test) the result was
failing due to the test being not found. After some searches, there is a
workaround.
Otherwise if you look to the recent test reports, a lot of tests are missing
> Fix missing tests cases

- src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java
- src/test/java/io/github/intellij/dlanguage/parser/DLanguageParserTest.java
- src/test/resources/gold/parser/e15876_1.d
- src/test/resources/gold/parser/expected/e15876_1.txt
fix parsing of ~test/fail_compilation/e15876_3.d~ test/fail_compilation/e15876_1.d
Closes #722
> 722: fix null pointer exception while parsing a dmd test

- src/main/java/io/github/intellij/dlanguage/lexer/DSyntaxHighlightingLexer.flex
> #723: Add support for alias types in the syntax highlighter

- src/main/kotlin/io/github/intellij/dlanguage/annotator/DStringLiteralAnnotator.kt
- src/test/resources/gold/highlighting/annotator/invalid_string_delimiters.d
Previously, the implementation was blindly considering that the last
character was always '"'. It’s actually a wrong assumption as a string
postfix can be added (c, w, d). The code now consider this and the error
annotation won’t highlight the '"' character even with postfix.
Related to #751
> Fix annotation ending when string delimiter has a string postfix

- src/main/jflex/io/github/intellij/dlanguage/lexer/DLanguageLexer.flex
- src/main/kotlin/io/github/intellij/dlanguage/annotator/DUnclosedCommentAnnotator.kt
- src/main/resources/META-INF/plugin.xml
- src/test/java/io/github/intellij/dlanguage/highlighting/DlangHighlightingLexerTest.java
- src/test/kotlin/io/github/intellij/dlanguage/annotator/DHighlightingAnnotatorTest.kt
- src/test/kotlin/io/github/intellij/dlanguage/lexer/DlangLexerTest.kt
- src/test/resources/gold/highlighting/annotator/unclosed_comment.d
- src/test/resources/gold/parser/expected/statements_unterminated_if.txt
Due to end of file not being handle in some state, the lexer was left in non initial state leading to errors.
Close #771
>  #771 fix multiline comments breaking highlighting

- src/main/kotlin/io/github/intellij/dlanguage/dub/packageConfig/inspections/DubPackageDependencyVisitor.kt
This was a leftover case, that happened during testing.
> Fix a potential exception

- src/main/java/io/github/intellij/dlanguage/psi/DTokenSets.java
- src/main/kotlin/io/github/intellij/dlanguage/DLanguage.kt
Replace deprecated method name by his new correct name.
Fix STRING_LITERAL token set.
set real value to getStringLiteralElements().
> Minor changes, no behavior change is expected

- dub/src/main/kotlin/io/github/intellij/dub/actions/DubBuildAction.kt
- dub/src/main/kotlin/io/github/intellij/dub/run/DubBuildRunner.kt
- dub/src/main/kotlin/io/github/intellij/dub/toolwindow/DubToolWindowPanel.kt
Closes #835 
Now, the run button correctly launch the application
> #835: Fix the run icon in DubToolWindow to correctly start the dub runner

- dub/src/main/kotlin/io/github/intellij/dub/highlighting/annotation/DubSyntaxAnnotator.kt
- src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/DExternalAnnotator.java
It’s explicitelly said in doc, if some is catch it must be re-thrown and it should not be logged. If the action was cancelled, the action was cancelled. Don’t panic about it.
> Don’t catch ProcessCancelledException to log them

- dub/src/main/kotlin/io/github/intellij/dub/actions/ProcessDLibs.kt
- src/main/java/io/github/intellij/dlanguage/actions/DFormatAction.java
- src/main/java/io/github/intellij/dlanguage/codeinsight/DCompletionProvider.java
- src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java
Also included a fix to prevent a severe warning in the log:
```
addEntity: symbolic id already exists. Replacing entity with the new one.
Symbolic id: LibraryId(name=sidero_image:colorimetry-~master, tableId=com.intellij.workspaceModel.storage.bridgeEntities.LibraryTableId$ProjectLibraryTableId@5f6e1199)
Existing entity data: LibraryEntityData(name=sidero_image:colorimetry-~master, tableId=com.intellij.workspaceModel.storage.bridgeEntities.LibraryTableId$ProjectLibraryTableId@5f6e1199, roots=[LibraryRoot(url=file://P:/ProjectSidero/image/colorimetry, type=LibraryRootTypeId(name=CLASSES), inclusionOptions=ROOT_ITSELF)], entitySource=FileInDirectory(directory=file://P:/ProjectSidero/image/.idea/libraries, fileNameId=10, projectLocation=DirectoryBased(projectDir=file://P:/ProjectSidero/image, …
```
> Fix #790 no read access in EDT, scope parameter in foreach and dformat action taking too long

- src/main/java/io/github/intellij/dlanguage/actions/DFormatAction.java
This rewrite of DFormatAction was brought on because I was getting 8-second+ freezes of IntelliJ.
It also happens to fix the mangling of Unicode characters in comments.
The code was inspired by a Go plugin and I've now used it for over 2 hours the only error I've gotten was by an Android plugin that for whatever reason is loaded with the dev IDE.
May close: https://github.com/intellij-dlanguage/intellij-dlanguage/issues/765
> Almost completely rewrite DFormatAction to improve performance and fix Unicode mangling

- debugger/src/main/java/uk/co/cwspencer/gdb/gdbmi/GdbMiParser2.java
- debugger/src/main/java/uk/co/cwspencer/ideagdb/debug/GdbValue.java
- dub/src/main/kotlin/io/github/intellij/dub/actions/ConfigureDToolsAction.kt
- dub/src/main/kotlin/io/github/intellij/dub/actions/DubBuildAction.kt
- dub/src/main/kotlin/io/github/intellij/dub/actions/ProcessDLibs.kt
- dub/src/main/kotlin/io/github/intellij/dub/project/DubListenerComponent.kt
- dub/src/main/kotlin/io/github/intellij/dub/toolwindow/DubToolWindowPanel.kt
- src/main/java/io/github/intellij/dlanguage/actions/DFormatAction.java
- src/main/java/io/github/intellij/dlanguage/actions/RestartDCD.java
- src/main/java/io/github/intellij/dlanguage/utils/DToolsNotificationAction.java
- src/main/kotlin/io/github/intellij/dlanguage/project/creation.kt
- src/main/kotlin/io/github/intellij/dlanguage/template/DlangContext.kt
- src/main/resources/META-INF/plugin.xml
A bunch of commits that were originated from Intellij's code inspection facilities.
Unfortunately, nothing was raised regarding nullability as was talked about in another ticket.
Of note is the getActionUpdateThread methods, turns out those exceptions aren't just there because the actions were running on BGT, it seems they were really running on EDT this entire time. By moving them to BGT the IDE is now really responsive, which I was very shocked about! Looks like my un-comfortability the last few days about this has been justified.
Oh, and I've talked with WebFreak about Dscanner and the full-line-length warnings we get. Yesterday they worked on custom formats and a few other things that could improve our support. However, they recommended that we switch to the report form (JSON) instead …
> Some intellij plugin inspection fixes

- dub/src/main/kotlin/io/github/intellij/dub/project/DubConfigurationParser.kt
I believe this will fix it.
The problem is it's running in the context of a read action, the invokeLater call should put it on to the EDT using a write action.
From ModalityState which configures this behavior:
> For these reasons, it's strongly advised to use Application.invokeLater methods everywhere instead of SwingUtilities.invokeLater(Runnable) and com.intellij.util.ui.UIUtil convenience methods.
> Attempted fix for issue #880

- src/main/kotlin/io/github/intellij/dlanguage/psi/references/DReference.kt
- src/main/kotlin/io/github/intellij/dlanguage/resolve/DResolveUtil.kt
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTestCase.kt
I discovered while doing some change in the resolve, that a test was wrong but was passing.
The class construction was resolved to the class definition even if a constructor was defined. But due to a wrong reference searching in setup step of tests, the reference found was the same as the wrong one find in the setup.
> Fix wrong test

- dub/src/main/kotlin/io/github/intellij/dub/run/DubBuildStackTraceFilter.kt
- dub/src/test/kotlin/io/github/intellij/dub/run/DubBuildSourceFileFilterTest.kt
- src/main/kotlin/io/github/intellij/dlanguage/run/DmdConsoleFilterProvider.kt
- src/main/resources/META-INF/plugin.xml
- src/test/kotlin/io/github/intellij/dlanguage/run/DmdBuildStackTraceFilterTest.kt
- Fix the stack trace filter for dub (file was not detected due to ending \n + link was missplassed in console due to wrong offset calculation)
- Add new stack trace filter for dmd bulid
I manually checked that file path were highlighted and pointing to the good location
> Improve links in console when building

- src/main/kotlin/io/github/intellij/dlanguage/resolve/DResolveUtil.kt
This also improve the behavior by ensuring that new won’t resolve a function.
> Fix regression of resolve brought by bbee600

- dub/src/main/kotlin/io/github/intellij/dub/run/DubBuildStackTraceFilter.kt
- dub/src/test/kotlin/io/github/intellij/dub/run/DubBuildSourceFileFilterTest.kt
At step to run rdmd, the first check was passing but then no match was found, this led to an unhandled exception. Change the logic to be more robust.
> Fix error when building plugin

- src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImplUtil.kt
- src/main/kotlin/io/github/intellij/dlanguage/stubs/index/StubIndexUtil.kt
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTestCase.kt
- src/test/resources/gold/resolve/anonymousEnumUsage/usage.d
- src/test/resources/gold/resolve/enumUsageWithEnumTypePrefix/usage.d
- src/test/resources/gold/resolve/enumUsageWithoutEnumTypePrefixShouldNotResolve/usage.d
Only anonymous enums can be accessed directly.
This unfortunately breaks the resolve of the enum values accessed correctly. This will require more work to support chained calls.
But at least, the enum members won’t be resolved when they should not.
> Fix wrong resolution for named enum values

- dub/src/main/kotlin/io/github/intellij/dub/project/DubProjectOpenProcessor.kt
- src/main/java/io/github/intellij/dlanguage/codeinsight/dcd/DCDCompletionClient.java
I also noticed that ``visitDeclaratorIdentifierList`` was missing when I built it, I stubbed it out locally but that isn't right.
It does concern me that we are doing more work than required and I have to later on remove modules when loading via dub.
I couldn't work out what introduced it, but anyway now it has the source directory set without the dialog from the exception.
> Fix issue #905, #790 and duplicative modules when loading via dub

- src/main/kotlin/io/github/intellij/dlanguage/utils/DUtil.kt
A static module constructor does not have a parent class or interface, then this method should return null.
The docs already says it can return null, so no need of !!
> Fix a potential null pointer exception

- src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java
This is part of the parser refactoring. The next step is to replace all .equals by standards == and the null pointer exceptions will belong to the past.
A side effect of this change is that while the parsing time remain the same, the file expansion in the project window is now much more faster (no need anymore to wait seconds on projects like DMD before the tree displays)
> Rewrite parser step 2 : Remove prefetching parsing

- src/main/java/io/github/intellij/dlanguage/parser/DLangParser.java
Remove .equals(IElementType) and replace them by == (Removing the potentials NullPointersExceptions)
Remove dead code and commented code
Closes #922 
Closes #578 
Closes #326
> Parser cleaning

- utils/src/main/kotlin/io/github/intellij/dlanguage/core.kt
Identifiers are case sensitives, so notify it overriding the isCaseSensitive() method.
add readResolve method
> DLanguage instance improvements

- src/main/java/io/github/intellij/dlanguage/psi/impl/DNamedStubbedPsiElementBase.java
With previous implementation, the new node was replaced by a Java node, so all references were lost after the rename. A reparse (text modification) was needed to rehave the PSI correct and references resolving back to what they should.
Tested by calling rename on a file and seeing the references still being referencing without other modification. A unit test can be added for this, to ensure that the renamed Psi node is still a valid D node.
> Fix the rename implementation

- .github/workflows/coverage.yml
To build generated PSI, it needs rdmd, so install it before generating coverage reports.
> Add dlang tools to coverage actions

- .github/workflows/coverage.yml
It seems that on CI the coveralls command start before all reports are generated. So start the coveralls only once the report is here.
> start coverall command after the generate report is finished

- dlang/plugin-impl/build.gradle.kts
Taking the absolute path of the report to prevent the report of the root module (partial) to be taken.
And automate the addition of kover application as dependency for the aggregated report.
> Fix the kover report path to take the aggregated report

- dlang/plugin-impl/build.gradle.kts
- errorreporting/build.gradle.kts
For some reason the "automatic apply" method does not work (the "kover" extension does not appear for them). So fallback to the manual method of adding them line by line.
Also removed errorreporting module as it’s not covered by test and don’t contains useful code to cover.
I checked in the aggregated report that psi-api classes and psi-impl classes appear
> Fix coverage of psi-* modules not included

- dlang/plugin-impl/build.gradle.kts
For some reason the hasExtension can return null even if the subproject has the extension applied. It may be a gradle regression or an expected (but strange) behavior from gradle.
> Fix coveralls ignoring some subproject sources

- dlang/plugin-impl/build.gradle.kts
This time it will work. I checked in the logs that no line was ignored/skipped due to plugin not knowing the source file.
I still don’t know how to have all project being evaluated before evaluate the coverallsJacoco task in order to have the sourceSets extension being applied to all projects. At least, this way works.
> Fix coverage

- scripts/types_regen_script.d
- src/main/kotlin/io/github/intellij/dlanguage/features/documentation/DSignatureDocGenerator.kt
With Psi simplification, the expression value may directly be a LiteralExpression instead of the whole tree of
assignExpression(.(.(.(literalExpression)))). Fix this behavior otherwise, we get a null when looking for an assignExpression where it’s actually a simple literalExpression.
> Fix null pointer exception in doc rendering due to wrong type

- build.gradle.kts
- dlang/psi-api/build.gradle.kts
- dlang/psi-impl/build.gradle.kts
- scripts/types_regen_script.d
- sdlang/build.gradle.kts
With this change, running `gradle clean` will delete the generated folders and so no artifact of a previous build will remain (useful when a Psi change happened).
> Delete generated folders (gen) when executing the clean task

- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/parser/DLangParser.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/CodeBlockElementType.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/DlangTypes.java
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/impl/DLanguageBlockStatementImpl.kt
- scripts/types_regen_script.d
Apparently this should optimize parsing in some cases (I didn’t see difference). All languages plugins do this, so it should be useful.
> Lazily parse statements blocks

- dlang/psi-impl/src/main/java/io/github/intellij/dlanguage/psi/impl/DNamedStubbedPsiElementBase.java
This is a leftover from the change of name being nullable. This is not @NotNull function, the interface marked this method as @Nullable and @NlsSafe.
> Fix illegal state exception with null return value

- src/main/kotlin/io/github/intellij/dlanguage/inspections/PossiblyUndefinedSymbol.kt
in `a.Foo!int;` Foo was not marked as undefined if `a` resolved but not `Foo`. This is now the case.
> Fix undefined symbol not marked as undefined with templates

- dub/src/main/resources/META-INF/io.github.intellij.dub.xml
For Dub Module, we depends on Json to check the validity of the schema (and so helps the user to determine if the dub.json is vadid and provide autocompletion). But since Intelij 2024.3, json was moved into his own module, so add it to allow the application to work correctly.
Closes #1028
> Fix(#1028): add missing declaration to json module in plugin.xml

- gradle/libs.versions.toml
Supersede #1017 
For some reason dependabot seems not check java dependencies
> Update intellij gradle plugin to 2.2.1

- dlang/psi-impl/src/main/java/io/github/intellij/dlanguage/psi/impl/named/DLanguageForeachTypeImpl.java
- src/test/kotlin/io/github/intellij/dlanguage/types/ForeachVariableTypeTest.kt
The support is not complete as a lot of advance semantic support is missing to properly handle everything, but at least add support for type resolution in simple cases of auto variables of foreach.
The code was made to be robust and return unknown type for all unsupported and illegal cases
> Add some type comprehension for foreach auto variables

- dlang/plugin-impl/src/main/resources/META-INF/plugin.xml
- src/main/kotlin/io/github/intellij/dlanguage/structure/DLanguageStructureAwareNavbar.kt
- src/main/kotlin/io/github/intellij/dlanguage/structure/DStructureViewFactory.kt
- src/main/kotlin/io/github/intellij/dlanguage/structure/DStructureViewModel.kt
With this feature, the navigation bar will show the current context more precisely (if we are in a fuction or in a class).
Note: no test was added because Jetbrains does not export his utility function to test it (the one it uses for Java and Kotlin)
Closes #951
> fix(951): add navigation aware navbar

- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/DlangPsiFileImpl.kt
If the index is not built we have no chance to be able to resolve object, so eagerly return otherwise we’ll get an IndexNotReadyException when looking into DModuleIndex.
> Fix a possible index not ready exception

- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/parser/DLangParser.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/CodeBlockElementType.kt
- src/test/resources/gold/parser/expected/statements_unterminated_if.txt
With some invalid code, the parser could stop eagerly and do not parse everyting. Add a recovery code to ensure that the whole text is covered by the builder and the IDE is happy.
This could be really improved (with better detection of errors and recovening in the parser itself but it will be done in a dedicated PR of better errors detections).
> Harden the code block element reparsing

- src/main/kotlin/io/github/intellij/dlanguage/features/DDocumentationProvider.kt
- src/main/kotlin/io/github/intellij/dlanguage/features/documentation/DDocGenerator.kt
- src/test/kotlin/io/github/intellij/dlanguage/features/DDocumentationProviderTest.kt
- src/test/resources/gold/documentation/example.d
This is a regression from the big PSI refactoring, now that the PSI is more simple, the logic for the documentation too. Also added a test to ensure this kind of regression won’t happen anymore.
Closes #1040
> fix(#1040): display the documentation when hovering an element

- dlang/plugin-impl/src/main/resources/META-INF/clion-only.xml
- dlang/plugin-impl/src/main/resources/META-INF/plugin.xml
This will allow to be able to create project for others IDE than Intellij and clion
Without this change the D application does not appear in clion. It does not affect intellij that don’t consider the DirectoryProcessors.
> Fix include names and always include DlangProjectGenerator

- src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt
- src/test/resources/gold/resolve/nestedStructMemberUsageShouldResolve/a.d
- src/test/resources/gold/resolve/nestedStructMemberUsageShouldResolve/b.d
This was actually fixed since the resolve refactoring and type support
Closes #488
> fix(#488): add a test for a nested static struct member usage

- .github/workflows/gradle.yml
- dlang/plugin-impl/src/main/resources/META-INF/plugin.xml
- gradle.properties
Minumun platform requirements bump to 2024.3 for 2 reasons:
UI PR that will require this minimum version for API
be able to upgrade kotlin 2
> Add support for platform version 251 (2025.1)

- build.gradle.kts
- dub/build.gradle.kts
optimize dependencies in modules, and fix the test by adding explicit dependency to platform tests
> Fix intellij 2025.1 tests

- src/main/java/io/github/intellij/dlanguage/highlighting/annotation/external/LinterHelper.java
If the project is closed, the action is probably cancelled. So checking if action is cancelled just before accessing the project.
Closes #1037
> fix(#1037): Try fixing project already closed during dsanner parsing

- src/main/kotlin/io/github/intellij/dlanguage/annotator/DHighlightingAnnotator.kt
some non basic types (like string) are actually an alias. But we colored them like keywords because they are so essentials(basics). This manual coloration was wrongly applied so the whole type was colorized and not only the "basic type".
**Before:**
**After:**
> Fix highlighting of certains elements

- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/annotator/DlangLiteralChecker.kt
- src/test/resources/gold/highlighting/annotator/invalid_literal_values.d
A missing casing in the check made that `0xbb` literal was incorrectly reported as empty hexadecimal integer
> Don’t report 0xff as empty hexadecimal integer value

- dub/src/main/kotlin/io/github/intellij/dub/project/settings/DubConfigurableProvider.kt
When no binary is selected DUB_KEY.path is null but the executablePath.text is never null, it is at minimum the empty string. This fix make the modification behavior correct when autodetection is used (empty path provided) on not defined path configured (autodetection).
> Fix the condition for onModify of dub binary path

- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/parser/DLangParser.kt
Should closes #1125 
Should also closes #1055 
I’m not able to verify it as my computer has a big enough stack to not trigger the overflow, but the while loop should remove the stack growth. That’s also why I didn’t added a test for it.
Majority of changes are just cleaning.
> Fix(#1125): Reduce the parser recursion stack when parsing comma exp

- dlang/psi-impl/src/main/jflex/io/github/intellij/dlanguage/lexer/DLanguageLexer.flex
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/lexer/DlangLexer.kt
- src/test/kotlin/io/github/intellij/dlanguage/lexer/DlangLexerTest.kt
you can’t yypushback on eof as eof do not progress.
before the fix, the lexer crashed and the file could not be displayed
> Fix some exception in the lexer when reaching eof

- dlang/psi-api/src/main/java/io/github/intellij/dlanguage/psi/DlangVisitor.java
- dlang/psi-api/src/main/java/io/github/intellij/dlanguage/psi/named/DLanguageModule.java
- dlang/psi-api/src/main/java/io/github/intellij/dlanguage/psi/named/DLanguagePackage.java
- dlang/psi-api/src/main/kotlin/io/github/intellij/dlanguage/psi/interfaces/DVisibility.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/ext/DLanguageQualifiedIdentifierImplMixin.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/impl/DLanguageImportDeclarationImpl.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/impl/DLanguageModuleImpl.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/impl/DLanguagePackageImpl.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/references/GenericExpressionElementReference.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/references/PackageReference.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/resolve/processor/GenericProcessor.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/resolve/processor/TypeProcessor.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/PsiScopesUtil.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/processor/PackageOrModuleProcessor.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/DResolveUtil.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImpl.kt
- scripts/types_regen_script.d
- src/test/kotlin/io/github/intellij/dlanguage/DLightPlatformCodeInsightFixtureTestCase.kt
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DImportsUsageResolveTest.kt
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTestCase.kt
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DScopedImportResolveTest.kt
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DSymbolNameLookupResolveTest.kt
Correctly resolve symbol imported with static import
Properly resolve symbols called by there fully qualified name
With this change the resolve algorithm of imported symbol is almost fully compliant with specs. Only one case is not correctly supported (see commented test for this), but this case is an "error" case (when there is a conflict due to 2 imports)
> Improve import resolution

- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/DlangPsiFileImpl.kt
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt
- src/test/resources/gold/resolve/functionCallUFCSWithoutImportShouldNotResolve/object.d
- src/test/resources/gold/resolve/functionCallUFCSWithoutImportShouldNotResolve/resolve.d
- src/test/resources/gold/resolve/functionCallUFCSWithoutImportShouldNotResolve/usage.d
When looking at object, previously a wrong argument allowed the algorithm to think that the element was in the object module and so allowing to search in imported modules from object. This resulted in resolved element while they should not.
> Ensure that element privately imported in object module are not checked

- dlang/plugin-impl/src/main/resources/META-INF/plugin.xml
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/PsiScopesUtil.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/psi/scope/processor/UFCSProcessor.kt
- dlang/psi-impl/src/main/kotlin/io/github/intellij/dlanguage/resolve/ScopeProcessorImpl.kt
- scripts/types_regen_script.d
- src/test/kotlin/io/github/intellij/dlanguage/resolve/DResolveTest.kt
- src/test/resources/gold/resolve/aliasValueWithSameNameAsAliasDeclarationShouldNotResolveToAliasDeclaration3/usage.d
- src/test/resources/gold/resolve/enumUsageWithoutEnumTypePrefixShouldNotResolve2/usage.d
- src/test/resources/gold/resolve/functionCallUFCSWithLocalSelectiveImportResolve2/other.d
- src/test/resources/gold/resolve/functionCallUFCSWithLocalSelectiveImportResolve2/resolve.d
- src/test/resources/gold/resolve/functionDeclarationInSameConditionalDeclarationBlockAsUsageShouldResolve/usage.d
- src/test/resources/gold/resolve/withStatementShouldResolveInnerElements/usage.d
Properly handle WithStatements
Fix resolve of second form of ConditionalCompilation (`version(Foo):`)
Add test to ensure named enum values are not accidentally resolved
Fix UFCS search when target is a template
> More reslove fixes

- src/main/kotlin/io/github/intellij/dlanguage/annotator/DStringLiteralAnnotator.kt
- src/main/kotlin/io/github/intellij/dlanguage/lexer/DDelimitedStringDelimiterLexer.kt
- src/main/kotlin/io/github/intellij/dlanguage/utils/DStringUtil.kt
- src/test/resources/gold/highlighting/annotator/invalid_string_delimiters.d
Now the closing delimiter is always the correct one and the check for invalid text after closing delimiter is properly placed.
> Fix delimited string checks and highligting
